//
// Created by james on 7/13/2026.
//

#include "abilities.h"
#include "characters.h"
#include "data/progression.h"

//--------------------------------------------------
// Ability Database
//--------------------------------------------------

static_assert(
    ABILITY_CATEGORY_SPELL == 0,
    "Spell rows rely on zero-initialized AbilityCategory metadata."
);
static_assert(
    SAVE_NONE == 0 && CONDITION_NONE == 0 && MAP_EFFECT_NONE == 0,
    "Ability rows rely on zero-initialized optional metadata."
);

const Ability abilityDatabase[] =
{
    {
        ABILITY_NONE,"None",ABILITY_MARTIAL,0,0,ACTION_STANDARD,DELIVERY_AUTOMATIC,TARGET_SELF,DURATION_INSTANT,{{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},0,ANIM_NONE,ABILITY_CATEGORY_NONE
    }, // ABILITY_NONE

    //------------------------------------------------
    // Universal Abilities
    //------------------------------------------------

    {
        ABILITY_FIRE_BREATH,"Fire Breath",ABILITY_MARTIAL,0,0,ACTION_STANDARD,DELIVERY_CONE,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_FIRE, 6, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BREATH,ABILITY_CATEGORY_MONSTER
    }, // ABILITY_FIRE_BREATH

    {
        ABILITY_HEAL,"Heal",ABILITY_MARTIAL,0,0,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_HEAL, DAMAGE_NONE, 8, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL,ABILITY_CATEGORY_MONSTER
    }, // ABILITY_HEAL

    {
        ABILITY_PARALYZE,"Paralyze",ABILITY_MARTIAL,0,0,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_PARALYZE, DAMAGE_NONE, 1, 0, 3 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_MONSTER
    }, // ABILITY_PARALYZE

    {
        ABILITY_POISON,"Poison",ABILITY_MARTIAL,0,0,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_POISON, DAMAGE_NONE, 2, 1, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_POISON,ABILITY_CATEGORY_MONSTER
    }, // ABILITY_POISON

    {
        ABILITY_REGENERATION,"Regeneration",ABILITY_MARTIAL,0,0,ACTION_STANDARD,DELIVERY_AUTOMATIC,TARGET_SELF,DURATION_INSTANT,{{ EFFECT_HEAL, DAMAGE_NONE, 2, 1, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL,ABILITY_CATEGORY_MONSTER
    }, // ABILITY_REGENERATION

    {
        ABILITY_SUMMON,"Summon",ABILITY_MARTIAL,0,0,ACTION_STANDARD,DELIVERY_TARGET,TARGET_EMPTY_TILE,DURATION_INSTANT,{{ EFFECT_SUMMON, DAMAGE_NONE, 1, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_MONSTER
    }, // ABILITY_SUMMON

{
    ABILITY_MELEE_ATTACK,
    "Melee Attack",ABILITY_MARTIAL,0,0,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_PHYSICAL, 1, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_ATTACK
},

{
    ABILITY_RANGED_ATTACK,"Ranged Attack",ABILITY_MARTIAL,0,0,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_PHYSICAL, 1, 0, 0 },
{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_ATTACK
},

    {
        ABILITY_CHANNEL_ENERGY,"Channel Energy",ABILITY_DIVINE,0,0,ACTION_STANDARD,DELIVERY_AREA,TARGET_ALL_ALLIES_AREA,DURATION_INSTANT,{{ EFFECT_HEAL, DAMAGE_POSITIVE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL,ABILITY_CATEGORY_CLASS_FEATURE
    },

    {
        ABILITY_TURN_UNDEAD,"Turn Undead",ABILITY_DIVINE,0,0,ACTION_STANDARD,DELIVERY_AUTOMATIC,TARGET_SELF,DURATION_INSTANT,{{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},0,ANIM_NONE,ABILITY_CATEGORY_CLASS_FEATURE,6,SAVE_WILL
    },

{
    ABILITY_POWER_ATTACK,"Power Attack",ABILITY_MARTIAL,0,0,ACTION_FREE,DELIVERY_AUTOMATIC,TARGET_SELF,DURATION_ROUNDS,{{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},0,ANIM_NONE,ABILITY_CATEGORY_CLASS_FEATURE
},
    //------------------------------------------------
    // Cantrips
    //------------------------------------------------

    {
        ABILITY_ACID_SPLASH,"Acid Splash",ABILITY_ARCANE,0,1,ACTION_STANDARD,DELIVERY_RANGED_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_ACID, 3, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_ACID_SPLASH
    }, // ABILITY_ACID_SPLASH

    {
        ABILITY_DISRUPT_UNDEAD,"Disrupt Undead",ABILITY_DIVINE,0,1,ACTION_STANDARD,DELIVERY_RANGED_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_POSITIVE, 6, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_DISRUPT_UNDEAD

    {
        ABILITY_GUIDANCE,"Guidance",ABILITY_DIVINE,0,1,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_ROUNDS,{{ EFFECT_BUFF_ATTACK, DAMAGE_NONE, 1, 0, 1 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_GUIDANCE

    {
        ABILITY_JOLT,"Jolt",ABILITY_ARCANE,0,1,ACTION_STANDARD,DELIVERY_RANGED_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_ELECTRIC, 3, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_LIGHTNING
    }, // ABILITY_JOLT

    {
        ABILITY_LIGHT,"Light",ABILITY_DIVINE,0,1,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 600 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},0,ANIM_NONE
    }, // ABILITY_LIGHT

    {
        ABILITY_RAY_OF_FROST,"Ray of Frost",ABILITY_ARCANE,0,1,ACTION_STANDARD,DELIVERY_RANGED_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_COLD, 3, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_RAY_OF_FROST

    {
        ABILITY_RESISTANCE,"Resistance",ABILITY_DIVINE,0,1,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_SAVE, DAMAGE_NONE, 1, 0, 1 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_RESISTANCE

    {
        ABILITY_SPARK,"Spark",ABILITY_ARCANE,0,1,ACTION_STANDARD,DELIVERY_RANGED_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_FIRE, 3, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_FIREBALL
    }, // ABILITY_SPARK

        //------------------------------------------------
    // Level 1
    //------------------------------------------------

    {
        ABILITY_BANE,"Bane",ABILITY_DIVINE,1,2,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_DEBUFF_ATTACK, DAMAGE_NONE, 1, 0, 5, CONDITION_BANE },{ EFFECT_DEBUFF_SAVE, DAMAGE_NONE, 1, 0, 5, CONDITION_BANE },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_NONE,ABILITY_CATEGORY_SPELL,6,SAVE_WILL
    }, // ABILITY_BANE

    {
        ABILITY_BLESS,"Bless",ABILITY_DIVINE,1,2,ACTION_STANDARD,DELIVERY_AREA,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_ATTACK, DAMAGE_NONE, 1, 0, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_BLESS

    {
        ABILITY_BURNING_HANDS,"Burning Hands",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_CONE,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_FIRE, 4, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_FIREBALL,ABILITY_CATEGORY_SPELL,3,SAVE_REFLEX,0,MAP_EFFECT_NONE,0,SAVE_EFFECT_HALF
    }, // ABILITY_BURNING_HANDS

    {
        ABILITY_CAUSE_FEAR,"Cause Fear",ABILITY_DIVINE,1,2,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_FEAR, DAMAGE_NONE, 1, 0, 3 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_FEAR
    }, // ABILITY_CAUSE_FEAR

    {
        ABILITY_COLOR_SPRAY,"Color Spray",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_CONE,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_STUN, DAMAGE_NONE, 0, 0, 2, CONDITION_STUNNED },{ EFFECT_BLIND, DAMAGE_NONE, 0, 0, 4, CONDITION_BLINDED },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_NONE,ABILITY_CATEGORY_SPELL,3,SAVE_WILL
    }, // ABILITY_COLOR_SPRAY

    {
        ABILITY_CURE_LIGHT_WOUNDS,"Cure Light Wounds",ABILITY_DIVINE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_HEAL, DAMAGE_NONE, 8, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL
    }, // ABILITY_CURE_LIGHT_WOUNDS

    {
        ABILITY_DOOM,"Doom",ABILITY_DIVINE,1,2,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_FEAR, DAMAGE_NONE, 1, 0, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_FEAR
    }, // ABILITY_DOOM

    {
        ABILITY_ENLARGE_PERSON,"Enlarge Person",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_STR, DAMAGE_NONE, 2, 0, 10 },{ EFFECT_DEBUFF_DEX, DAMAGE_NONE, 2, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_BLESS
    }, // ABILITY_ENLARGE_PERSON

    {
        ABILITY_EXPEDITIOUS_RETREAT,"Expeditious Retreat",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_SELF,DURATION_COMBAT,{{ EFFECT_BUFF_SPEED, DAMAGE_NONE, 30, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_EXPEDITIOUS_RETREAT

    {
        ABILITY_GREASE,"Grease",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_ROUNDS,{{ EFFECT_PRONE, DAMAGE_NONE, 0, 0, 0, CONDITION_PRONE },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_SPELL,6,SAVE_REFLEX,1,MAP_EFFECT_GREASE,3
    }, // ABILITY_GREASE

    {
        ABILITY_MAGE_ARMOR,"Mage Armor",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_AC, DAMAGE_NONE, 4, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_MAGE_ARMOR

    {
        ABILITY_MAGIC_MISSILE,"Magic Missile",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_FORCE, 4, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_MAGIC_MISSILE,ABILITY_CATEGORY_SPELL,6
    }, // ABILITY_MAGIC_MISSILE

    {
        ABILITY_OBSCURING_MIST,"Obscuring Mist",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_BUFF_MISS_CHANCE, DAMAGE_NONE, 20, 0, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_OBSCURING_MIST

    {
        ABILITY_RAY_OF_ENFEEBLEMENT,"Ray of Enfeeblement",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_RANGED_TOUCH,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_DEBUFF_STR, DAMAGE_NONE, 4, 0, 5, CONDITION_ENFEEBLED },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_SPELL,6
    }, // ABILITY_RAY_OF_ENFEEBLEMENT

    {
        ABILITY_REDUCE_PERSON,"Reduce Person",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_DEX, DAMAGE_NONE, 2, 0, 10 },{ EFFECT_DEBUFF_STR, DAMAGE_NONE, 2, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_BLESS
    }, // ABILITY_REDUCE_PERSON

    {
        ABILITY_REMOVE_FEAR,"Remove Fear",ABILITY_DIVINE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_REMOVE_CONDITION, DAMAGE_NONE, EFFECT_FEAR, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL
    }, // ABILITY_REMOVE_FEAR

    {
        ABILITY_SHIELD,"Shield",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_SELF,DURATION_COMBAT,{{ EFFECT_BUFF_AC, DAMAGE_NONE, 4, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_SHIELD

    {
        ABILITY_SHOCKING_GRASP,"Shocking Grasp",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_ELECTRIC, 6, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_LIGHTNING
    }, // ABILITY_SHOCKING_GRASP

    {
        ABILITY_SLEEP,"Sleep",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_ROUNDS,{{ EFFECT_SLEEP, DAMAGE_NONE, 0, 0, 3, CONDITION_SLEEPING },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_SLEEP,ABILITY_CATEGORY_SPELL,6,SAVE_WILL
    }, // ABILITY_SLEEP

    {
        ABILITY_SNOWBALL,"Snowball",ABILITY_ARCANE,1,2,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_COLD, 6, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_SNOWBALL

    //------------------------------------------------
    // Level 2
    //------------------------------------------------

    {
        ABILITY_ACID_ARROW,"Acid Arrow",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_RANGED_TOUCH,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_DAMAGE, DAMAGE_ACID, 0, 0, 0, CONDITION_NONE, 2, 4 },{ EFFECT_DAMAGE_OVER_TIME, DAMAGE_ACID, 0, 0, 2, CONDITION_NONE, 2, 4 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_ACID_SPLASH,ABILITY_CATEGORY_SPELL,6
    }, // ABILITY_ACID_ARROW

    {
        ABILITY_BEARS_ENDURANCE,"Bear's Endurance",ABILITY_DIVINE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_CON, DAMAGE_NONE, 4, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_BEARS_ENDURANCE

    {
        ABILITY_BLINDNESS,"Blindness",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_BLIND, DAMAGE_NONE, 1, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_BLINDNESS

    {
        ABILITY_BLUR,"Blur",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_MISS_CHANCE, DAMAGE_NONE, 20, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLUR
    }, // ABILITY_BLUR

    {
        ABILITY_BULLS_STRENGTH,"Bull's Strength",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_STR, DAMAGE_NONE, 4, 0, 10, CONDITION_BULLS_STRENGTH },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_BULLS_STRENGTH

    {
        ABILITY_CATS_GRACE,"Cat's Grace",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_DEX, DAMAGE_NONE, 4, 0, 10, CONDITION_CATS_GRACE },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_CATS_GRACE

    {
        ABILITY_CURE_MODERATE_WOUNDS,"Cure Moderate Wounds",ABILITY_DIVINE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_HEAL, DAMAGE_NONE, 16, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL
    }, // ABILITY_CURE_MODERATE_WOUNDS

    {
        ABILITY_EAGLES_SPLENDOR,"Eagle's Splendor",ABILITY_DIVINE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_CHA, DAMAGE_NONE, 4, 0, 10, CONDITION_EAGLES_SPLENDOR },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_EAGLES_SPLENDOR

    {
        ABILITY_FLAMING_SPHERE,"Flaming Sphere",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_DAMAGE, DAMAGE_FIRE, 6, 2, 3 },{ EFFECT_BURN, DAMAGE_FIRE, 2, 1, 3 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_FIREBALL
    }, // ABILITY_FLAMING_SPHERE

    {
        ABILITY_GLITTERDUST,"Glitterdust",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_BLIND, DAMAGE_NONE, 1, 0, 3 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_GLITTERDUST

    {
        ABILITY_HOLD_PERSON,"Hold Person",ABILITY_DIVINE,2,4,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_PARALYZE, DAMAGE_NONE, 1, 0, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_HOLD_PERSON

    {
        ABILITY_LESSER_RESTORATION,"Lesser Restoration",ABILITY_DIVINE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_REMOVE_CONDITION, DAMAGE_NONE, 1, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL
    }, // ABILITY_LESSER_RESTORATION

    {
        ABILITY_OWLS_WISDOM,"Owl's Wisdom",ABILITY_DIVINE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_WIS, DAMAGE_NONE, 4, 0, 10, CONDITION_OWLS_WISDOM },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_OWLS_WISDOM

    {
        ABILITY_RESIST_ENERGY,"Resist Energy",ABILITY_DIVINE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_DAMAGE_RESISTANCE, DAMAGE_NONE, 10, 5, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_RESIST_ENERGY

    {
        ABILITY_SCORCHING_RAY,"Scorching Ray",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_RANGED_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_FIRE, 8, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_FIREBALL
    }, // ABILITY_SCORCHING_RAY

    {
        ABILITY_SHATTER,"Shatter",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_SONIC, 8, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_SPELL,6,SAVE_FORTITUDE,1,MAP_EFFECT_NONE,0,SAVE_EFFECT_HALF
    }, // ABILITY_SHATTER

    {
        ABILITY_TOUCH_OF_IDIOCY,"Touch of Idiocy",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_DEBUFF_ATTACK, DAMAGE_NONE, 2, 0, 5 },{ EFFECT_DEBUFF_DAMAGE, DAMAGE_NONE, 2, 0, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_NONE
    }, // ABILITY_TOUCH_OF_IDIOCY

    {
        ABILITY_WEB,"Web",ABILITY_ARCANE,2,4,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_ENTANGLED, DAMAGE_NONE, 0, 0, 0, CONDITION_WEBBED },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_SPELL,6,SAVE_REFLEX,1,MAP_EFFECT_WEB,0
    }, // ABILITY_WEB

    //------------------------------------------------
    // Level 3
    //------------------------------------------------

    {
        ABILITY_BESTOW_CURSE,"Bestow Curse",ABILITY_DIVINE,3,6,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_DEBUFF_ATTACK, DAMAGE_NONE, 4, 0, 10, CONDITION_CURSED },{ EFFECT_DEBUFF_SAVE, DAMAGE_NONE, 4, 0, 10, CONDITION_CURSED },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_NONE,ABILITY_CATEGORY_SPELL,0,SAVE_WILL
    }, // ABILITY_BESTOW_CURSE

    {
        ABILITY_CURE_SERIOUS_WOUNDS,"Cure Serious Wounds",ABILITY_DIVINE,3,6,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_HEAL, DAMAGE_NONE, 24, 3, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL
    }, // ABILITY_CURE_SERIOUS_WOUNDS

    {
        ABILITY_DEEP_SLUMBER,"Deep Slumber",ABILITY_ARCANE,3,6,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_SLEEP, DAMAGE_NONE, 1, 0, 8 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_SLEEP
    }, // ABILITY_DEEP_SLUMBER

    {
        ABILITY_FIREBALL,"Fireball",ABILITY_ARCANE,3,6,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_FIRE, 6, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_FIREBALL,ABILITY_CATEGORY_SPELL,6,SAVE_REFLEX,1,MAP_EFFECT_NONE,0,SAVE_EFFECT_HALF
    }, // ABILITY_FIREBALL

    {
        ABILITY_HASTE,"Haste",ABILITY_ARCANE,3,6,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_SPEED, DAMAGE_NONE, 6, 0, 5, CONDITION_HASTED },{ EFFECT_BUFF_BONUS_ATTACK, DAMAGE_NONE, 1, 0, 5, CONDITION_HASTED },{ EFFECT_BUFF_ATTACK, DAMAGE_NONE, 1, 0, 5, CONDITION_HASTED },{ EFFECT_BUFF_AC, DAMAGE_NONE, 1, 0, 5, CONDITION_HASTED }},4,ANIM_BLESS
    }, // ABILITY_HASTE

    {
        ABILITY_HEROISM,"Heroism",ABILITY_ARCANE,3,6,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_ATTACK, DAMAGE_NONE, 2, 0, 10, CONDITION_HEROISM },{ EFFECT_BUFF_SAVE, DAMAGE_NONE, 2, 0, 10, CONDITION_HEROISM },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_BLESS
    }, // ABILITY_HEROISM

    {
        ABILITY_LIGHTNING_BOLT,"Lightning Bolt",ABILITY_ARCANE,3,6,ACTION_STANDARD,DELIVERY_LINE,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_ELECTRIC, 6, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_LIGHTNING,ABILITY_CATEGORY_SPELL,6,SAVE_REFLEX,0,MAP_EFFECT_NONE,0,SAVE_EFFECT_HALF
    }, // ABILITY_LIGHTNING_BOLT

    {
        ABILITY_MAGIC_CIRCLE,"Magic Circle",ABILITY_DIVINE,3,6,ACTION_STANDARD,DELIVERY_AREA,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_AC, DAMAGE_NONE, 2, 0, 10 },{ EFFECT_BUFF_SAVE, DAMAGE_NONE, 2, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_BLESS
    }, // ABILITY_MAGIC_CIRCLE

    {
        ABILITY_PROTECTION_FROM_ENERGY,"Protection from Energy",ABILITY_DIVINE,3,6,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_DAMAGE_RESISTANCE, DAMAGE_NONE, 20, 10, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_PROTECTION_FROM_ENERGY

    {
        ABILITY_REMOVE_DISEASE,"Remove Disease",ABILITY_DIVINE,3,6,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_REMOVE_CONDITION, DAMAGE_NONE, 1, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL
    }, // ABILITY_REMOVE_DISEASE

    {
        ABILITY_SEARING_LIGHT,"Searing Light",ABILITY_DIVINE,3,6,ACTION_STANDARD,DELIVERY_RANGED_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_POSITIVE, 8, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_SEARING_LIGHT

    {
        ABILITY_SLOW,"Slow",ABILITY_ARCANE,3,6,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_DEBUFF_SPEED, DAMAGE_NONE, 6, 0, 5, CONDITION_SLOWED },{ EFFECT_DEBUFF_ATTACK, DAMAGE_NONE, 1, 0, 5, CONDITION_SLOWED },{ EFFECT_DEBUFF_AC, DAMAGE_NONE, 1, 0, 5, CONDITION_SLOWED },{ EFFECT_DEBUFF_SAVE, DAMAGE_NONE, 1, 0, 5, CONDITION_SLOWED }},4,ANIM_NONE,ABILITY_CATEGORY_SPELL,6,SAVE_WILL
    }, // ABILITY_SLOW

    {
        ABILITY_STINKING_CLOUD,"Stinking Cloud",ABILITY_ARCANE,3,6,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_STUN, DAMAGE_NONE, 1, 0, 3 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_STINKING_CLOUD

    {
        ABILITY_VAMPIRIC_TOUCH,"Vampiric Touch",ABILITY_ARCANE,3,6,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ENEMY,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_NEGATIVE, 6, 2, 0 },{ EFFECT_HEAL, DAMAGE_NONE, 3, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_HEAL
    }, // ABILITY_VAMPIRIC_TOUCH

    //------------------------------------------------
    // Level 4
    //------------------------------------------------

    {
        ABILITY_BLACK_TENTACLES,"Black Tentacles",ABILITY_ARCANE,4,8,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_ENTANGLED, DAMAGE_NONE, 1, 0, 10 },{ EFFECT_DAMAGE, DAMAGE_PHYSICAL, 4, 2, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_NONE
    }, // ABILITY_BLACK_TENTACLES

    {
        ABILITY_CONFUSION,"Confusion",ABILITY_ARCANE,4,8,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_CONFUSE, DAMAGE_NONE, 1, 0, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_CONFUSION

    {
        ABILITY_CURE_CRITICAL_WOUNDS,"Cure Critical Wounds",ABILITY_DIVINE,4,8,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_HEAL, DAMAGE_NONE, 32, 4, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL
    }, // ABILITY_CURE_CRITICAL_WOUNDS

    {
        ABILITY_FEAR,"Fear",ABILITY_DIVINE,4,8,ACTION_STANDARD,DELIVERY_CONE,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_FEAR, DAMAGE_NONE, 1, 0, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_FEAR
    }, // ABILITY_FEAR

    {
        ABILITY_FIRE_SHIELD,"Fire Shield",ABILITY_ARCANE,4,8,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_SELF,DURATION_COMBAT,{{ EFFECT_DAMAGE_RESISTANCE, DAMAGE_FIRE, 20, 5, 10 },{ EFFECT_BURN, DAMAGE_FIRE, 4, 1, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_FIREBALL
    }, // ABILITY_FIRE_SHIELD

    {
        ABILITY_FREEDOM_OF_MOVEMENT,"Freedom of Movement",ABILITY_DIVINE,4,8,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_REMOVE_CONDITION, DAMAGE_NONE, EFFECT_ENTANGLED, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_FREEDOM_OF_MOVEMENT

    {
        ABILITY_GREATER_INVISIBILITY,"Greater Invisibility",ABILITY_ARCANE,4,8,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_INVISIBLE, DAMAGE_NONE, 1, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLUR
    }, // ABILITY_GREATER_INVISIBILITY

    {
        ABILITY_ICE_STORM,"Ice Storm",ABILITY_ARCANE,4,8,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_COLD, 10, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_SPELL,6,SAVE_REFLEX,1,MAP_EFFECT_NONE,0,SAVE_EFFECT_HALF
    }, // ABILITY_ICE_STORM

    {
        ABILITY_RESTORATION,"Restoration",ABILITY_DIVINE,4,8,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_REMOVE_CONDITION, DAMAGE_NONE, 1, 0, 0 },{ EFFECT_HEAL, DAMAGE_NONE, 8, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_HEAL
    }, // ABILITY_RESTORATION

    {
        ABILITY_STONESKIN,"Stoneskin",ABILITY_ARCANE,4,8,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_DAMAGE_RESISTANCE, DAMAGE_PHYSICAL, 10, 5, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_STONESKIN

    {
        ABILITY_WALL_OF_FIRE,"Wall of Fire",ABILITY_ARCANE,4,8,ACTION_STANDARD,DELIVERY_LINE,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_DAMAGE, DAMAGE_FIRE, 6, 2, 5 },{ EFFECT_BURN, DAMAGE_FIRE, 2, 1, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_FIREBALL
    }, // ABILITY_WALL_OF_FIRE

        //------------------------------------------------
    // Level 5+
    //------------------------------------------------

    {
        ABILITY_CHAIN_LIGHTNING,"Chain Lightning",ABILITY_ARCANE,5,10,ACTION_STANDARD,DELIVERY_TARGET,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_ELECTRIC, 10, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_LIGHTNING
    }, // ABILITY_CHAIN_LIGHTNING

    {
        ABILITY_CLOUDKILL,"Cloudkill",ABILITY_ARCANE,5,10,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_COMBAT,{{ EFFECT_POISON, DAMAGE_NONE, 4, 2, 5 },{ EFFECT_DAMAGE, DAMAGE_NONE, 2, 1, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_POISON
    }, // ABILITY_CLOUDKILL

    {
        ABILITY_CONE_OF_COLD,"Cone of Cold",ABILITY_ARCANE,5,10,ACTION_STANDARD,DELIVERY_CONE,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_COLD, 10, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE,ABILITY_CATEGORY_SPELL,6,SAVE_REFLEX,0,MAP_EFFECT_NONE,0,SAVE_EFFECT_HALF
    }, // ABILITY_CONE_OF_COLD

    {
        ABILITY_DOMINATE_PERSON,"Dominate Person",ABILITY_DIVINE,5,10,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_CONFUSE, DAMAGE_NONE, 1, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_DOMINATE_PERSON

    {
        ABILITY_FLAME_STRIKE,"Flame Strike",ABILITY_DIVINE,5,10,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_INSTANT,{{ EFFECT_DAMAGE, DAMAGE_FIRE, 10, 2, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_FIREBALL,ABILITY_CATEGORY_SPELL,6,SAVE_REFLEX,1,MAP_EFFECT_NONE,0,SAVE_EFFECT_HALF
    }, // ABILITY_FLAME_STRIKE

    {
        ABILITY_GREATER_HEROISM,"Greater Heroism",ABILITY_DIVINE,5,10,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_ATTACK, DAMAGE_NONE, 4, 0, 10 },{ EFFECT_BUFF_SAVE, DAMAGE_NONE, 4, 0, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_BLESS
    }, // ABILITY_GREATER_HEROISM

    {
        ABILITY_HOLD_MONSTER,"Hold Monster",ABILITY_DIVINE,5,10,ACTION_STANDARD,DELIVERY_TARGET,TARGET_ENEMY,DURATION_COMBAT,{{ EFFECT_PARALYZE, DAMAGE_NONE, 1, 0, 5 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_NONE
    }, // ABILITY_HOLD_MONSTER

    {
        ABILITY_MASS_CURE_LIGHT_WOUNDS,"Mass Cure Light Wounds",ABILITY_DIVINE,5,10,ACTION_STANDARD,DELIVERY_AREA,TARGET_ALLY,DURATION_INSTANT,{{ EFFECT_HEAL, DAMAGE_NONE, 8, 1, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL
    }, // ABILITY_MASS_CURE_LIGHT_WOUNDS

    {
        ABILITY_MIND_BLANK,"Mind Blank",ABILITY_ARCANE,5,10,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_SAVE, DAMAGE_NONE, 8, 0, 20 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_MIND_BLANK

    {
        ABILITY_REGENERATE,"Regenerate",ABILITY_DIVINE,5,10,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_HEAL, DAMAGE_NONE, 4, 2, 10 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_HEAL
    }, // ABILITY_REGENERATE

    {
        ABILITY_TRUE_SEEING,"True Seeing",ABILITY_DIVINE,5,10,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_REMOVE_CONDITION, DAMAGE_NONE, EFFECT_INVISIBLE, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS
    }, // ABILITY_TRUE_SEEING

    {
        ABILITY_WALL_OF_STONE,"Wall of Stone",ABILITY_ARCANE,5,10,ACTION_STANDARD,DELIVERY_LINE,TARGET_AREA,DURATION_COMBAT, {{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 10 },
      { EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},0,ANIM_NONE
    }, // ABILITY_WALL_OF_STONE

    {
        ABILITY_SOUND_BURST,"Sound Burst",ABILITY_DIVINE,2,4,ACTION_STANDARD,DELIVERY_AREA,TARGET_AREA,DURATION_INSTANT,
        {{ EFFECT_DAMAGE, DAMAGE_SONIC, 6, 1, 0 }, { EFFECT_STUN, DAMAGE_NONE, 0, 0, 1, CONDITION_STUNNED },
         { EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_NONE,ABILITY_CATEGORY_SPELL,6,SAVE_FORTITUDE,1,MAP_EFFECT_NONE,0,SAVE_EFFECT_HALF
    }, // ABILITY_SOUND_BURST

    { ABILITY_DIVINE_FAVOR,"Divine Favor",ABILITY_DIVINE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_SELF,DURATION_COMBAT,{{ EFFECT_BUFF_ATTACK, DAMAGE_NONE, 1, 0, 5, CONDITION_DIVINE_FAVOR },{ EFFECT_BUFF_DAMAGE, DAMAGE_NONE, 1, 0, 5, CONDITION_DIVINE_FAVOR },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},2,ANIM_BLESS },
    { ABILITY_SHIELD_OF_FAITH,"Shield of Faith",ABILITY_DIVINE,1,2,ACTION_STANDARD,DELIVERY_TOUCH,TARGET_ALLY,DURATION_COMBAT,{{ EFFECT_BUFF_AC, DAMAGE_NONE, 2, 0, 10, CONDITION_SHIELD_OF_FAITH },{ EFFECT_NONE, DAMAGE_NONE, 0, 0, 0 }},1,ANIM_BLESS },

};

//--------------------------------------------------
// Helper Functions
//--------------------------------------------------


static_assert(
    (sizeof(abilityDatabase) / sizeof(abilityDatabase[0])) == ABILITY_MAX,
    "Ability database does not match AbilityID enum."
);


const Ability* getAbility(AbilityID id)
{
    if (!isValidAbility(id))
        return nullptr;

    return &abilityDatabase[id];
}

const char* getAbilityName(AbilityID id)
{
    const Ability* ability = getAbility(id);

    if (ability == nullptr)
        return "Unknown";

    return ability->name;
}

bool isValidAbility(AbilityID id)
{
    return id > ABILITY_NONE && id < ABILITY_MAX;
}

bool knowsAbility(const Character& character,
                  AbilityID id)
{
    if (!isValidAbility(id))
        return false;

    uint8_t abilityCount = character.magic.knownAbilityCount;

    if (abilityCount > MAX_KNOWN_ABILITIES)
        abilityCount = MAX_KNOWN_ABILITIES;

    for (uint8_t i = 0; i < abilityCount; i++)
    {
        if (character.magic.knownAbilities[i] == id)
            return true;
    }

    return false;
}

bool learnAbility(Character& character,
                  AbilityID id)
{
    if (!isValidAbility(id) || knowsAbility(character, id) ||
        character.magic.knownAbilityCount >= MAX_KNOWN_ABILITIES)
    {
        return false;
    }

    character.magic.knownAbilities[
        character.magic.knownAbilityCount++] = id;
    return true;
}

bool forgetAbility(Character& character,
                   AbilityID id)
{
    if (!isValidAbility(id) ||
        character.magic.knownAbilityCount > MAX_KNOWN_ABILITIES)
    {
        return false;
    }

    for (uint8_t i = 0; i < character.magic.knownAbilityCount; i++)
    {
        if (character.magic.knownAbilities[i] != id)
            continue;

        for (uint8_t j = i;
             j + 1 < character.magic.knownAbilityCount;
             j++)
        {
            character.magic.knownAbilities[j] =
                character.magic.knownAbilities[j + 1];
        }

        character.magic.knownAbilityCount--;
        character.magic.knownAbilities[
            character.magic.knownAbilityCount] = ABILITY_NONE;
        return true;
    }

    return false;
}

static void clearKnownAbilities(Character& character)
{
    character.magic.knownAbilityCount = 0;

    for (uint8_t i = 0; i < MAX_KNOWN_ABILITIES; i++)
        character.magic.knownAbilities[i] = ABILITY_NONE;
}

void initializeCharacterMagic(Character& character)
{
    character.magic.currentMP = 0;
    character.magic.maxMP = 0;
    character.magic.arcaneCaster = false;
    character.magic.divineCaster = false;
    character.magic.learning = {};

    clearKnownAbilities(character);

    if (character.characterClass == CLASS_WIZARD)
    {
        character.magic.arcaneCaster = true;
    }
    else if (character.characterClass == CLASS_CLERIC)
    {
        character.magic.divineCaster = true;
    }

    refreshCharacterMagicProgression(character);
    character.magic.currentMP = character.magic.maxMP;
}

void restoreCharacterMagic(
    Character& character,
    int savedCurrentMP,
    const AbilityID* savedKnownAbilities,
    uint8_t savedKnownAbilityCount)
{
    initializeCharacterMagic(character);

    if (savedKnownAbilities != nullptr)
    {
        clearKnownAbilities(character);

        uint8_t abilityCount = savedKnownAbilityCount;
        if (abilityCount > MAX_KNOWN_ABILITIES)
            abilityCount = MAX_KNOWN_ABILITIES;

        for (uint8_t i = 0; i < abilityCount; i++)
            learnAbility(character, savedKnownAbilities[i]);

        // Merge mandatory class/level spells idempotently after restoring the
        // exact saved spellbook. Scroll-learned entries are never cleared.
        refreshCharacterMagicProgression(character);
    }

    character.magic.currentMP = clampCurrentMPForCharacter(
        character, savedCurrentMP);
}
